### ISSUE TITLE
Server Stop Should be changed

### ISSUE THREAD

**Issue by dirtycajunrice** [Skyost/SkyDocs#6]
When creating a systemd service file to have SkyDocs run in the background, systemd sends keystrokes to the service to make sure the application is still alive. Because you have set entering anything to stop the server, it causes the service to exit.

Service file (skydocs.service):

```
[Unit]
Description=SkyDocs

[Service]
WorkingDirectory=/opt/SkyDocs/docs/
ExecStart=/bin/bash /opt/SkyDocs/docs/serve.sh
User=root
Type=simple

[Install]
WantedBy=multi-user.target
```

I propose you change the "Stop Server" command to Ctrl^C or Ctrl^D to not only be in line with other applications but to resolve this issue.

Thanks!

**Comment by Skyost** [comment]
I don't know systemd services very well, are you allowed to pass arguments to SkyDocs ? If yes, I can create a simple parameter that disables the "Enter anything to stop the server" system.

**Comment by dirtycajunrice** [comment]
yeah. It runs it exactly as typed in the command line. So flags will too

**Comment by Skyost** [comment]
Hey,    
Everything has been fixed in the new commit. You can download the latest dev build [here](https://circleci.com/api/v1.1/project/github/Skyost/SkyDocs/latest/artifacts/0/$CIRCLE_ARTIFACTS/SkyDocs-SNAPSHOT.jar).

The argument system has been changed a bit, you can see available commands using `java -jar SkyDocs.jar help`.
